// react-cliente/src/components/cliente/Calculadora.jsx
import React from 'react'
import Navbar from '../../layout/Navbar'

function Calculadora() {
  return (
    <div>
<Navbar></Navbar>
<div className="flex-grow">
      <div className="px-4 py-6 h-20 text-center lg:mt-8"></div>
      <div className="flex w-full items-center justify-center flex-col lg:flex-row lg:mx-10 lg:mt-14">
        <div className="bg-purple-100 flex flex-col justify-center items-center h-72 w-80 lg:h-96 p-4">
          <div className="h-64 w-72"></div>
        </div>
        <div className="w-80 lg:h-96 bg-white p-4">
          <form>
            <br />
            <h5>2. Color</h5>
            <label htmlFor="sc" className="sr-only">
              Underline select
            </label>
            <select id="sc" className="block py-2.5 px-0 w-full text-sm text-gray-500 bg-transparent border-0 border-b-2 border-gray-200 dark:text-gray-400 dark:border-gray-700 focus:outline-none focus:ring-0 focus:border-gray-200 peer">
              <option value="">Seleccionar color</option>
              {/* Mapea los colores */}
            </select>
            <br />
            <label htmlFor="rellenoRange" className="block mb-2">
              3. Relleno
            </label>
            <div className="flex justify-center">
              <input
                id="rellenoRange"
                type="range"
                min="10"
                max="100"
                value="50"
                step="10"
                className="mt-2 mx-2 w-full h-2 bg-yellow-200 rounded-lg appearance-none cursor-pointer dark:bg-gray-700"
              />
              <h4 id="nr">50%</h4>
            </div>
            <br />
            <h5>4. Tamaño</h5>
            <div className="flex justify-center">
              <input
                id="sizeRange"
                type="range"
                min="0.5"
                max="1.5"
                value="1"
                step="0.05"
                className="mt-2 mx-2 w-full h-2 bg-yellow-200 rounded-lg appearance-none cursor-pointer dark:bg-gray-700 border-black"
              />
              <h4 className="w-10" id="sr">
                100%
              </h4>
            </div>
            <br />
            <h5>Precio:</h5>
            <h5 id="price">80000</h5>
            <button
              id="xd"
              type="submit"
              className="text-black bg-yellow-300 hover:bg-yellow-400 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue"
            >
              Comprar
            </button>
          </form>
        </div>
      </div>
    </div>


    </div>
    
  )
}

export default Calculadora

// angular/src/app/components/cliente/calculadora/calculadora.component.ts
import { Component,OnInit,ElementRef,ViewChild} from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { color } from 'src/app/models/color';
import { producto } from 'src/app/models/producto';
import { CrudServiceService } from 'src/app/services/crud-service.service';
import Swal from 'sweetalert2';
declare const StlViewer:any;
@Component({
  selector: 'app-calculadora',
  templateUrl: './calculadora.component.html',
  styleUrls: ['./calculadora.component.css']
})
export class CalculadoraComponent implements OnInit {
  listColores:color[]= [];

  productoForm: FormGroup;
  id: string | null;
  botonTexto = "Ingresar Color";

  constructor(private fb:FormBuilder,private _service:CrudServiceService,private router:Router,private aRoute:ActivatedRoute){
    this.productoForm=this.fb.group({
      color:[''],
      relleno:[''],
      tamano:[''],
      estado:['']
    })
    this.id=this.aRoute.snapshot.paramMap.get('id');
  }

  

  @ViewChild('stlCont',{static:true}) stlCont!:ElementRef<HTMLDivElement>;
  stl_viewer:any;
  colorSeleccionado: string= "#70f0ae";
  ngOnInit(){
    this.initStlViewer(this.colorSeleccionado);
    this.obtenerColores();
  }

  obtenerColores(){
    this._service.obtenerTodos(`colores`).subscribe({
      next:(data)=>{
        this.listColores=data;
      },
      error:()=>{

      },
      complete:()=>{
        console.log(this.listColores)
      }
    })
  }


  
  initStlViewer(colorCodigo:string) {
    this.stl_viewer = new StlViewer(this.stlCont.nativeElement,{models: [{ id: 0, filename: "dino.stl",color:colorCodigo,rotationx:Math.PI*1.5 }],auto_rotate:true});
  }

  cambiarColor(color:string){
    this.colorSeleccionado=color;
    this.stl_viewer.set_color(0,color);
  }


  agregarProducto(){
    const PRODUCTO: producto = {
      color:this.productoForm.get('color')?.value,
      relleno:this.productoForm.get('relleno')?.value || 50,
      tamano:this.productoForm.get('tamano')?.value || 1,
      volumen:this.productoForm.get('relleno')?.value*this.productoForm.get('tamano')?.value || 50,
      estado:true
    }
    console.log(PRODUCTO)

    if(this.id===null){

    this._service.guardar(PRODUCTO,"productos").subscribe({
      complete: ()=>{
        Swal.fire({
          icon: 'success',
          title: 'El producto ha sido creado correctamente',
          showConfirmButton: false,
          timer: 2000
        })
        this.productoForm.reset()

      },
      error: (e)=>{
        Swal.fire({
          icon: 'error',
          title: 'Hubo un error al crear el producto intentelo denuevo',
          showConfirmButton: false,
          timer: 2000
        })
        this.productoForm.reset()
      },
    }
    )
  }
  }
  


}

<div class="flex-grow">
    <app-navbar></app-navbar>
    <div class="px-4 py-6 h-20 text-center lg:mt-8">
</div> 
 <div class="flex w-full items-center justify-center flex-col lg:flex-row lg:mx-10 lg:mt-14">

        <div  class="bg-purple-100 flex flex-col justify-center items-center h-72 w-80  lg:h-96 p-4"  >
            <div #stlCont class="h-64 w-72" ></div>
        </div>
        <div class=" w-80  lg:h-96 bg-white p-4">
            <form [formGroup]="productoForm" (ngSubmit)="agregarProducto()">
        
            <br>
            <h5>2.Color</h5>
            <label for="sc" class="sr-only">Underline select</label>
            <select formControlName="color"  id="sc"  class="block py-2.5 px-0 w-full text-sm text-gray-500 bg-transparent border-0 border-b-2 border-gray-200  dark:text-gray-400 dark:border-gray-700 focus:outline-none focus:ring-0 focus:border-gray-200 peer">
                <option  *ngFor="let color of listColores" value="{{color._id}}" >{{color.nombre}}</option>
            </select>
            <br>
            <label for="rellenoRange" class="block mb-2">3.Relleno</label>

            <div class="flex justify-center">
            <input formControlName="relleno" id="rellenoRange" type="range" min="10" max="100" value="50" step="10" class="mt-2 mx-2 w-full h-2 bg-yellow-200 rounded-lg appearance-none cursor-pointer dark:bg-gray-700">
            <h4 id="nr" >50%</h4>

            
        </div>
        <br>
            <h5>4.Tamaño</h5>
            
            <div class="flex justify-center">
                <input formControlName="tamano"  id="sizeRange" type="range" min="0.5" max="1.5" value="1" step="0.05" class="mt-2 mx-2 w-full h-2 bg-yellow-200 rounded-lg appearance-none cursor-pointer dark:bg-gray-700 border-black">
                <h4 class="w-10" id="sr" >100%</h4>
    
                
            </div>
           
            <br>
            <h5>Precio:</h5>
            <h5 id="price">{{80000}}</h5>
            <button  id="xd" type="submit" class="text-black bg-yellow-300 hover:bg-yellow-400 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800 disabled:bg-yellow-200">Comprar</button>
        </form>
        </div>
    </div>
