// react-cliente/src/components/admin/CrearEmpleado.jsx
import React from 'react'
import { Link } from 'react-router-dom'
import NavbarAdmin from '../../layout/NavbarAdmin'
import NavbarLateral from '../../layout/NavbarLateral'

function CrearEmpleado() {
  return (
    <div>

<div class="flex">
  <NavbarLateral></NavbarLateral>
  <div class="flex-grow">
      <NavbarAdmin></NavbarAdmin>
      <div class="px-4 py-6 h-20 text-center lg:mt-8">
      <h1 class="text-4xl font-bold text-gray-900">Empleados</h1>
  </div>



  
<div class="flex items-center flex-col  lg:mx-10 lg:mt-14">
  <div class="w-full max-w-xs md:max-w-md ">
    <form id="formColor" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
      <div class="mb-6">
        <label for="codigoName" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Nombre</label>
        <input type="text" id="codigoName" class="h-10 bg-gray-50 border border-gray-300 text-gray-900  text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 " formControlName="nombre" placeholder="Elias" required/>
      </div>
      <div class="mb-6">
        <label for="codigoName" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Usuario</label>
        <input type="text" id="codigoName" class="h-10 bg-gray-50 border border-gray-300 text-gray-900  text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Seth" formControlName="user" required/>
      </div>
      <div class="mb-6">
        <label for="codigoName" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Contraseña</label>
        <input type="password" id="codigoName" class="h-10 bg-gray-50 border border-gray-300 text-gray-900  text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="*********" formControlName="contrasena" required/>
      </div>
      
 
      <div class="flex justify-evenly">
          <button id="submitColor" type="submit" class="text-black bg-green-100 hover:bg-green-200 focus:ring-4 focus:outline-none focus:ring-green-300 font-medium rounded-lg text-sm w-4/12 py-2.5 text-center  disabled:bg-gray-400 disabled:cursor-not-allowed disabled:pointer-events-none">Crear Emple</button>
          <Link to="/admin/listar-empleado" class="text-black bg-yellow-100 hover:bg-yellow-200 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-sm w-4/12  py-2.5 text-center">Ver Emple</Link>
      </div>
      
    </form>
    <p class="text-center text-gray-500 text-xs">
    </p>
  </div>
 

</div>

</div>
</div>
    </div>
  )
}

export default CrearEmpleado

// angular/src/app/components/admin/empleados/crear-empleado/crear-empleado.component.ts
import { Component,OnInit,ElementRef,ViewChild} from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { usuario } from 'src/app/models/usuario';
import { CrudServiceService } from 'src/app/services/crud-service.service';
import Swal from 'sweetalert2';

@Component({
  selector: 'app-crear-empleado',
  templateUrl: './crear-empleado.component.html',
  styleUrls: ['./crear-empleado.component.css']
})
export class CrearEmpleadoComponent implements OnInit{
  empleadoForm: FormGroup;
  id: string | null;
  botonTexto = "Ingresar Empleado";

  constructor(private fb:FormBuilder,private _service:CrudServiceService,private router:Router,private aRoute:ActivatedRoute){
    this.empleadoForm=this.fb.group({
      nombre:['',Validators.required],
      user:['',Validators.required],
      contrasena:['',Validators.required],
      rol:[''],
      estado:['']
    })
    this.id=this.aRoute.snapshot.paramMap.get('id');
  }

  ngOnInit(){
    if(this.id===null){
    }else{
    this.esEditar();
    }
  }




  agregarEmpleado(){
    console.log(this.empleadoForm)

    const EMPLEADO: usuario = {
      nombre:this.empleadoForm.get('nombre')?.value,
      user:this.empleadoForm.get('user')?.value,
      contrasena:this.empleadoForm.get('contrasena')?.value,
      rol:'empleado',
      estado:true
    }

    if(this.id===null){

    this._service.guardar(EMPLEADO,"usuarios").subscribe({
      complete: ()=>{
        Swal.fire({
          icon: 'success',
          title: 'El empleado ha sido creado correctamente',
          showConfirmButton: false,
          timer: 2000
        })
        this.empleadoForm.reset()

      },
      error: (e)=>{
        Swal.fire({
          icon: 'error',
          title: 'Hubo un error al crear el empleado intentelo denuevo',
          showConfirmButton: false,
          timer: 2000
        })
        this.empleadoForm.reset()
      },
    }
    )
  }else{
    this._service.actualizar(EMPLEADO,"usuarios",this.id).subscribe({
      complete: ()=>{
        Swal.fire({
          icon: 'success',
          title: 'El empleado ha sido actualizado correctamente',
          showConfirmButton: false,
          timer: 2000
        })
        this.router.navigate(['/admin/listar-empleado']);

      },
      error: (e)=>{
        Swal.fire({
          icon: 'error',
          title: 'Hubo un error al actualizar el empleado intentelo denuevo',
          showConfirmButton: false,
          timer: 2000
        })
      },
    }
    )

  }
  }


  esEditar(){
    if (this.id!==null){
      this.botonTexto='Editar Codigo'
      this._service.obtenerUno("usuarios",this.id).subscribe({
        next: (data)=>{
          this.empleadoForm.setValue({
            nombre:data.nombre,
            user:data.user,
            contrasena:data.contrasena,
            rol:data.rol,
            estado:data.estado
          })
        }

      })
    }
  
}


}

<div class="flex">
  <app-navbar-lateral></app-navbar-lateral>
  <div class="flex-grow">
      <app-navbar-superior></app-navbar-superior>
      <div class="px-4 py-6 h-20 text-center lg:mt-8">
      <h1 class="text-4xl font-bold text-gray-900">Empleados</h1>
  </div>

  <!-- inicio de la tabla -->


  
<div class="flex items-center flex-col  lg:mx-10 lg:mt-14">
  <div class="w-full max-w-xs md:max-w-md ">
    <form id="formColor" [formGroup]="empleadoForm" (ngSubmit)="agregarEmpleado()" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
      <div class="mb-6">
        <label for="codigoName" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Nombre</label>
        <input type="text" id="codigoName" class="h-10 bg-gray-50 border border-gray-300 text-gray-900  text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 " formControlName="nombre" placeholder="Elias" required/>
        <div class="text-red-600" *ngIf="empleadoForm.get('nombre')?.hasError('required')&&empleadoForm.get('nombre')?.touched">El campo no debe estar vacio</div>
      </div>
      <div class="mb-6">
        <label for="codigoName" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Usuario</label>
        <input type="text" id="codigoName" class="h-10 bg-gray-50 border border-gray-300 text-gray-900  text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Seth" formControlName="user" required/>
        <div class="text-red-600" *ngIf="empleadoForm.get('user')?.hasError('required')&&empleadoForm.get('user')?.touched">El campo no debe estar vacio</div>
      </div>
      <div class="mb-6">
        <label for="codigoName" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Contraseña</label>
        <input type="password" id="codigoName" class="h-10 bg-gray-50 border border-gray-300 text-gray-900  text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="*********" formControlName="contrasena" required/>
        <div class="text-red-600" *ngIf="empleadoForm.get('contrasena')?.hasError('required')&&empleadoForm.get('contrasena')?.touched">El campo no debe estar vacio</div>
      </div>
      
 
      <div class="flex justify-evenly">
          <button id="submitColor" type="submit" class="text-black bg-green-100 hover:bg-green-200 focus:ring-4 focus:outline-none focus:ring-green-300 font-medium rounded-lg text-sm w-4/12 py-2.5 text-center  disabled:bg-gray-400 disabled:cursor-not-allowed disabled:pointer-events-none" [disabled]="empleadoForm.invalid">{{botonTexto}}</button>
          <a routerLink="/admin/listar-empleado" class="text-black bg-yellow-100 hover:bg-yellow-200 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-sm w-4/12  py-2.5 text-center">Ver Emple</a>
      </div>
      
    </form>
    <p class="text-center text-gray-500 text-xs">
    </p>
  </div>
 

</div>
<!-- fin de la tabla -->

</div>
</div>
