// angular/src/app/components/admin/codigos/crear-codigo/crear-codigo.component.ts
import { Component,OnInit,ElementRef,ViewChild} from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { codigo } from 'src/app/models/codigo';
import { CrudServiceService } from 'src/app/services/crud-service.service';
import Swal from 'sweetalert2';
@Component({
  selector: 'app-crear-codigo',
  templateUrl: './crear-codigo.component.html',
  styleUrls: ['./crear-codigo.component.css']
})
export class CrearCodigoComponent implements OnInit {
  codigoForm: FormGroup;
  id: string | null;
  botonTexto = "Ingresar Codigo";

  constructor(private fb:FormBuilder,private _service:CrudServiceService,private router:Router,private aRoute:ActivatedRoute){
    this.codigoForm=this.fb.group({
      clave:['',Validators.required],
      fechaInicio:['',Validators.required],
      fechaFinal:['',Validators.required],
      descuento:['',Validators.required],
      estado:['']
    })
    this.id=this.aRoute.snapshot.paramMap.get('id');
  }

  ngOnInit(){
    if(this.id===null){
    }else{
    this.esEditar();
    }
  }




  agregarCodigo(){
    console.log(this.codigoForm)

    const CODIGO: codigo = {
      clave:this.codigoForm.get('clave')?.value,
      fechaInicio:this.codigoForm.get('fechaInicio')?.value,
      fechaFinal:this.codigoForm.get('fechaFinal')?.value,
      descuento:this.codigoForm.get('descuento')?.value,
      estado:true
    }

    if(this.id===null){

    this._service.guardar(CODIGO,"codigos").subscribe({
      complete: ()=>{
        Swal.fire({
          icon: 'success',
          title: 'El codigo ha sido creado correctamente',
          showConfirmButton: false,
          timer: 2000
        })
        this.codigoForm.reset()

      },
      error: (e)=>{
        Swal.fire({
          icon: 'error',
          title: 'Hubo un error al crear el codigo intentelo denuevo',
          showConfirmButton: false,
          timer: 2000
        })
        this.codigoForm.reset()
      },
    }
    )
  }else{
    this._service.actualizar(CODIGO,"codigos",this.id).subscribe({
      complete: ()=>{
        Swal.fire({
          icon: 'success',
          title: 'El codigo ha sido actualizado correctamente',
          showConfirmButton: false,
          timer: 2000
        })
        this.router.navigate(['/admin/listar-codigo']);

      },
      error: (e)=>{
        Swal.fire({
          icon: 'error',
          title: 'Hubo un error al actualizar el codigo intentelo denuevo',
          showConfirmButton: false,
          timer: 2000
        })
      },
    }
    )

  }
  }


  esEditar(){
    if (this.id!==null){
      this.botonTexto='Editar Codigo'
      this._service.obtenerUno("codigos",this.id).subscribe({
        next: (data)=>{
          this.codigoForm.setValue({
            clave:data.clave,
            fechaInicio:data.fechaInicio,
            fechaFinal:data.fechaFinal,
            descuento:data.descuento,
            estado:data.estado
          })
        }

      })
    }
  
}


}

<div class="flex">
  <app-navbar-lateral></app-navbar-lateral>
  <div class="flex-grow">
      <app-navbar-superior></app-navbar-superior>
      <div class="px-4 py-6 h-20 text-center lg:mt-8">
      <h1 class="text-4xl font-bold text-gray-900">Codigos</h1>
  </div>

  <!-- inicio de la tabla -->


  
<div class="flex items-center flex-col  lg:mx-10 lg:mt-14">
  <div class="w-full max-w-xs md:max-w-md ">
    <form id="formColor" [formGroup]="codigoForm" (ngSubmit)="agregarCodigo()" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
      <div class="mb-6">
        <label for="codigoName" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Nombre codigo</label>
        <input type="text" id="codigoName" class="h-10 bg-gray-50 border border-gray-300 text-gray-900  text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 " formControlName="clave" placeholder="qasdasdaw" required/>
        <div class="text-red-600" *ngIf="codigoForm.get('clave')?.hasError('required')&&codigoForm.get('clave')?.touched">El campo no debe estar vacio</div>
      </div>
      <div class="mb-6">
        <label for="codigoName" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Fecha Inicio</label>
        <input type="date" id="codigoName" class="h-10 bg-gray-50 border border-gray-300 text-gray-900  text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" formControlName="fechaInicio" required/>
        <div class="text-red-600" *ngIf="codigoForm.get('fechaInicio')?.hasError('required')&&codigoForm.get('fechaInicio')?.touched">El campo no debe estar vacio</div>
      </div>
      <div class="mb-6">
        <label for="codigoName" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Fecha Final</label>
        <input type="date" id="codigoName" class="h-10 bg-gray-50 border border-gray-300 text-gray-900  text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" formControlName="fechaFinal" required/>
        <div class="text-red-600" *ngIf="codigoForm.get('fechaFinal')?.hasError('required')&&codigoForm.get('fechaFinal')?.touched">El campo no debe estar vacio</div>
      </div>
      
      <div class="mb-6">
        <label for="codigoName" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Descuento</label>
        <input type="number" id="codigoName" class="h-10 bg-gray-50 border border-gray-300 text-gray-900  text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" formControlName="descuento" placeholder="0.25" required/>
        <div class="text-red-600" *ngIf="codigoForm.get('descuento')?.hasError('required')&&codigoForm.get('descuento')?.touched">El campo no debe estar vacio</div>
      </div>
          
      <div class="flex justify-evenly">
          <button id="submitColor" type="submit" class="text-black bg-green-100 hover:bg-green-200 focus:ring-4 focus:outline-none focus:ring-green-300 font-medium rounded-lg text-sm w-4/12 py-2.5 text-center  disabled:bg-gray-400 disabled:cursor-not-allowed disabled:pointer-events-none" [disabled]="codigoForm.invalid">{{botonTexto}}</button>
          <a routerLink="/admin/listar-codigo" class="text-black bg-yellow-100 hover:bg-yellow-200 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-sm w-4/12  py-2.5 text-center">Ver Codigos</a>
      </div>
      
    </form>
    <p class="text-center text-gray-500 text-xs">
    </p>
  </div>
 

</div>
<!-- fin de la tabla -->

</div>
</div>

// react-cliente/src/components/admin/CrearCodigo.jsx
import React from 'react'
import { Link } from 'react-router-dom'
import NavbarAdmin from '../../layout/NavbarAdmin'
import NavbarLateral from '../../layout/NavbarLateral'

function CrearCodigo() {
  return (
    <div>

<div class="flex">
  <NavbarLateral></NavbarLateral>
  <div class="flex-grow">
      <NavbarAdmin></NavbarAdmin>
      <div class="px-4 py-6 h-20 text-center lg:mt-8">
      <h1 class="text-4xl font-bold text-gray-900">Codigos</h1>
  </div>
  
<div class="flex items-center flex-col  lg:mx-10 lg:mt-14">
  <div class="w-full max-w-xs md:max-w-md ">
    <form id="formColor"  class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
      <div class="mb-6">
        <label for="codigoName" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Nombre codigo</label>
        <input type="text" id="codigoName" class="h-10 bg-gray-50 border border-gray-300 text-gray-900  text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 " formControlName="clave" placeholder="qasdasdaw" required/>
      </div>
      <div class="mb-6">
        <label for="codigoName" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Fecha Inicio</label>
        <input type="date" id="codigoName" class="h-10 bg-gray-50 border border-gray-300 text-gray-900  text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" formControlName="fechaInicio" required/>
      </div>
      <div class="mb-6">
        <label for="codigoName" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Fecha Final</label>
        <input type="date" id="codigoName" class="h-10 bg-gray-50 border border-gray-300 text-gray-900  text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" formControlName="fechaFinal" required/>
      </div>
      
      <div class="mb-6">
        <label for="codigoName" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Descuento</label>
        <input type="number" id="codigoName" class="h-10 bg-gray-50 border border-gray-300 text-gray-900  text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" formControlName="descuento" placeholder="0.25" required/>
      </div>
          
      <div class="flex justify-evenly">
          <button id="submitColor" type="submit" class="text-black bg-green-100 hover:bg-green-200 focus:ring-4 focus:outline-none focus:ring-green-300 font-medium rounded-lg text-sm w-4/12 py-2.5 text-center  disabled:bg-gray-400 disabled:cursor-not-allowed disabled:pointer-events-none">Crear Codigo</button>
          <Link to="/admin/listar-codigo" class="text-black bg-yellow-100 hover:bg-yellow-200 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-sm w-4/12  py-2.5 text-center">Ver Codigos</Link>
      </div>
      
    </form>
    <p class="text-center text-gray-500 text-xs">
    </p>
  </div>
 

</div>

</div>
</div>
    </div>
  )
}

export default CrearCodigo
