// react-cliente/src/components/admin/CrearColor.jsx
import React from 'react'
import { Link } from 'react-router-dom'
import NavbarAdmin from '../../layout/NavbarAdmin'
import NavbarLateral from '../../layout/NavbarLateral'

function CrearColor() {
  return (
    <div className="flex">
    <NavbarLateral />
    <div className="flex-grow">
      <NavbarAdmin />
      <div className="px-4 py-6 h-20 text-center lg:mt-8">
        <h1 className="text-4xl font-bold text-gray-900">Colores</h1>
      </div>
      <div className="flex items-center flex-col lg:flex-row lg:mx-10 lg:mt-14">
        <div className="mx-2 bg-white flex items-center flex-col h-72 w-80 md:w-4/5 lg:mx-0 lg:h-96">
          <form action="" id="formColor" className="px-5 py-5 flex justify-center flex-col h-full w-4/5">
            <div className="mb-6">
              <label htmlFor="colorName" className="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Nombre color</label>
              <input type="text" id="colorName" className="h-10 bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" formControlName="nombre" placeholder="Verde Pastel" required/>
            </div>
            <div className="mb-6">
              <label htmlFor="colorCode" className="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Codigo Color</label>
              <div className="flex border border-gray-300 rounded-lg h-10 relative overflow-hidden">
                <input   type="color" className="h-14 -top-2 -left-1 absolute appearance-none border-0" />
                <input  type="text" formControlName="codigo" id="colorCode"  className="bg-gray-50 ml-10 text-gray-900 text-sm focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" maxlength="7"/>
              </div>
              </div>
  
              <div class="flex justify-evenly">
                  <button id="submitColor" type="submit" class="text-black bg-green-100 hover:bg-green-200 focus:ring-4 focus:outline-none focus:ring-green-300 font-medium rounded-lg text-sm w-4/12 py-2.5 text-center  disabled:bg-gray-400 disabled:cursor-not-allowed disabled:pointer-events-none">Crear Color</button>
                  <Link to="/admin/listar-color" class="text-black bg-yellow-100 hover:bg-yellow-200 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-sm w-4/12  py-2.5 text-center">Ver Colores</Link>
              </div>
          </form>               
      </div> 
      <div  class="bg-purple-100 flex flex-col justify-center items-center h-72 w-80 md:w-4/5 lg:h-96">
          <div  class="h-full w-full cursor-crosshair	">
          </div>
      </div>
    </div>
  
  </div>
  </div>
  )
}

export default CrearColor

// angular/src/app/components/admin/colores/crear-color/crear-color.component.ts
import { Component,OnInit,ElementRef,ViewChild} from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { color } from 'src/app/models/color';
import { CrudServiceService } from 'src/app/services/crud-service.service';
import Swal from 'sweetalert2';
declare const StlViewer:any;

@Component({
  selector: 'app-crear-color',
  templateUrl: './crear-color.component.html',
  styleUrls: ['./crear-color.component.css']
})
export class CrearColorComponent implements OnInit {
  colorForm: FormGroup;
  id: string | null;
  botonTexto = "Ingresar Color";

  constructor(private fb:FormBuilder,private _service:CrudServiceService,private router:Router,private aRoute:ActivatedRoute){
    this.colorForm=this.fb.group({
      nombre:['',Validators.required],
      codigo:['',[Validators.required,Validators.minLength(7),Validators.maxLength(7),Validators.pattern(/^#[0-9A-Fa-f]{6}$/)]],
      estado:['']
    })
    this.id=this.aRoute.snapshot.paramMap.get('id');
  }


  @ViewChild('stlCont',{static:true}) stlCont!:ElementRef<HTMLDivElement>;
  stl_viewer:any;
  colorSeleccionado: string= "#70f0ae";
  ngOnInit(){
    if(this.id===null){
    this.initStlViewer(this.colorSeleccionado);
    }
    this.esEditar();
  }


  
  initStlViewer(colorCodigo:string) {
    this.stl_viewer = new StlViewer(this.stlCont.nativeElement,{models: [{ id: 0, filename: "dino.stl",color:colorCodigo,rotationx:Math.PI*1.5 }],auto_rotate:true});
  }

  cambiarColor(color:string){
    this.colorSeleccionado=color;
    this.colorForm.get('codigo')!.setValue(color);
    this.colorForm.get('codigo')!.markAsTouched(); 
    this.stl_viewer.set_color(0,color);
  }


  agregarColor(){
    console.log(this.colorForm)

    const COLOR: color = {
      nombre:this.colorForm.get('nombre')?.value,
      codigo:this.colorSeleccionado,
      estado:true
    }

    if(this.id===null){

    this._service.guardar(COLOR,"colores").subscribe({
      complete: ()=>{
        Swal.fire({
          icon: 'success',
          title: 'El color ha sido creado correctamente',
          showConfirmButton: false,
          timer: 2000
        })
        this.colorForm.reset()

      },
      error: (e)=>{
        Swal.fire({
          icon: 'error',
          title: 'Hubo un error al crear el color intentelo denuevo',
          showConfirmButton: false,
          timer: 2000
        })
        this.colorForm.reset()
      },
    }
    )
  }else{
    this._service.actualizar(COLOR,"colores",this.id).subscribe({
      complete: ()=>{
        Swal.fire({
          icon: 'success',
          title: 'El color ha sido actualizado correctamente',
          showConfirmButton: false,
          timer: 2000
        })
        this.router.navigate(['/dashboard/ver-colores']);

      },
      error: (e)=>{
        Swal.fire({
          icon: 'error',
          title: 'Hubo un error al actualizar el color intentelo denuevo',
          showConfirmButton: false,
          timer: 2000
        })
      },
    }
    )

  }
  }


  esEditar(){
    if (this.id!==null){
      this.botonTexto='Editar Color'
      this._service.obtenerUno("colores",this.id).subscribe({
        next: (data)=>{
          this.initStlViewer(data.codigo)
          this.colorForm.setValue({
            nombre:data.nombre,
            codigo:data.codigo,
            estado:data.estado
          })
          this.cambiarColor(data.codigo)
        }

      })
    }
  
}


}

<div class="flex">
    <app-navbar-lateral></app-navbar-lateral>
    <div class="flex-grow">
        <app-navbar-superior></app-navbar-superior>
        <div class="px-4 py-6 h-20 text-center lg:mt-8">
        <h1 class="text-4xl font-bold text-gray-900">Colores</h1>
    </div>

    <!-- inicio de la tabla -->
<div class="flex items-center flex-col lg:flex-row lg:mx-10 lg:mt-14">
    <div class="mx-2 bg-white flex items-center flex-col h-72 w-80 md:w-4/5 lg:mx-0 lg:h-96">
        <form action="" id="formColor" [formGroup]="colorForm" (ngSubmit)="agregarColor()"  class="px-5 py-5 flex justify-center flex-col h-full w-4/5">
            <div class="mb-6">
              <label for="colorName" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Nombre color</label>
              <input type="text" id="colorName" class="h-10 bg-gray-50 border border-gray-300 text-gray-900  text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" formControlName="nombre" placeholder="Verde Pastel" required/>
              <div class="text-red-600" *ngIf="colorForm.get('nombre')?.hasError('required')&&colorForm.get('nombre')?.touched">El campo no debe estar vacio</div>
            </div>
            <div class="mb-6">
                <label for="colorCode" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Codigo Color</label>
                <div class="flex border border-gray-300 rounded-lg h-10 relative overflow-hidden">
                    <input #selectColor (input)="cambiarColor(selectColor.value)" type="color"  class="h-14 -top-2 -left-1 absolute appearance-none border-0" [value]="colorSeleccionado"/>
                    <input #colorCode (input)="cambiarColor(colorCode.value)" [value]="colorSeleccionado" type="text" formControlName="codigo" id="colorCode" placeholder={{colorSeleccionado}} class="bg-gray-50 ml-10  text-gray-900 text-sm  focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" maxlength="7" />
                </div>
                
                <div class="text-red-600" *ngIf="colorForm.get('codigo')?.hasError('required')&& colorForm.get('codigo')?.touched" >El campo no debe estar vacio</div>
                <div class="text-red-600" *ngIf="colorForm.get('codigo')?.hasError('minlength')&& colorForm.get('codigo')?.touched" >El color debe tener minimo 7 digitos</div>
                <div class="text-red-600" *ngIf="colorForm.get('codigo')?.hasError('pattern')&& colorForm.get('codigo')?.touched" >El formato del color es incorrecto</div>
            </div>
            <div class="flex justify-evenly">
                <button id="submitColor" type="submit" class="text-black bg-green-100 hover:bg-green-200 focus:ring-4 focus:outline-none focus:ring-green-300 font-medium rounded-lg text-sm w-4/12 py-2.5 text-center  disabled:bg-gray-400 disabled:cursor-not-allowed disabled:pointer-events-none" [disabled]="colorForm.invalid">{{botonTexto}}</button>
                <a routerLink="/admin/listar-color" class="text-black bg-yellow-100 hover:bg-yellow-200 focus:ring-4 focus:outline-none focus:ring-yellow-300 font-medium rounded-lg text-sm w-4/12  py-2.5 text-center">Ver Colores</a>
            </div>
        </form>               
    </div> 
    <div  class="bg-purple-100 flex flex-col justify-center items-center h-72 w-80 md:w-4/5 lg:h-96">
        <div #stlCont class="h-full w-full cursor-crosshair	">
        </div>
    </div>
  </div>
  <!-- fin de la tabla -->

</div>
</div>
