// react-cliente/src/components/admin/ListarColor.jsx
import React,{useEffect, useState} from 'react'
import { Link } from 'react-router-dom'
import NavbarLateral from '../../layout/NavbarLateral'
import NavbarAdmin from '../../layout/NavbarAdmin'

function ListarColor() {

    const [backenData, setBackenData] = useState([{}])
  
    useEffect (()=>{
      fetch("http://localhost:4000/api/colores").then(
        response => response.json()
      ).then(
        data => setBackenData(data)
      )
    },[])
  return (
    <div>
        <div class="flex">
    <NavbarLateral></NavbarLateral>
    <div class="flex-grow">
        <NavbarAdmin></NavbarAdmin>
        <div class="px-4 py-6 h-20 text-center lg:mt-8">
        <h1 class="text-4xl font-bold text-gray-900">Colores</h1>
    </div>

    <div class="overflow-hidden mx-auto  w-3/4 px-4 sm:px-8">
        <div class="py-1">
            <div class="my-2 flex flex-row justify-between flex-wrap">
                <Link to="/admin/crear-color" class="my-1 text-black bg-yellow-100 hover:bg-yellow-200 w-24 text-sm h-10 rounded-lg font-medium py-2.5 text-center">Crear Color</Link>
            </div>
            </div>
            <div class="-mx-4 flex justify-center sm:-mx-8 px-4 sm:px-8 py-4 ">
                <div class="w-full  h-112 shadow rounded-lg ">
                    <div class="h-80 bg-white overflow-auto">
                    <table class="text-center w-full ">
                        <thead>
                            <tr >
                                <th class=" py-3 border-b-2 border-gray-200 bg-gray-100 text-xs font-semibold text-gray-600 uppercase tracking-wider"></th>
                                <th class=" py-3 border-b-2 border-gray-200 bg-gray-100 text-xs font-semibold text-gray-600 uppercase tracking-wider">Nombre</th>
                                <th class=" py-3 border-b-2 border-gray-200 bg-gray-100 text-xs font-semibold text-gray-600 uppercase tracking-wider">Codigo</th>
                                <th class=" py-3 border-b-2 border-gray-200 bg-gray-100 text-xs font-semibold text-gray-600 uppercase tracking-wider">Estado</th>
                                <th class=" py-3 border-b-2 border-gray-200 bg-gray-100 text-xs font-semibold text-gray-600 uppercase tracking-wider">Acciones</th>
                            </tr>
                        </thead>
                        {(typeof backenData === 'undefined') ?(
          <p>Loading...</p>
        ):(backenData.map((color, i)=>
        <tbody key={i}>
                            <tr class="h-14" >
                                <td class="px-5 border-b border-gray-200 bg-white text-sm">
                                    <input  type="checkbox" name="" id="" />
                                </td>
                                <td class="px-5 border-b border-gray-200 bg-white text-sm">
                                    <p class="text-gray-900 whitespace-nowrap">{color.nombre}</p>
                                </td>
                                <td class="px-5 border-b border-gray-200 bg-white text-sm">
                                    <p class="text-gray-900 whitespace-nowrap">{color.codigo}</p>
                                </td>
    
                            
                                <td class="px-5 border-b border-gray-200 bg-white text-sm">
                                    <p class="text-gray-900 whitespace-nowrap" >{color.estado ? 'activo':'inactivo'}</p>
                                
                                </td>
                                <td class="px-5 border-b border-gray-200 bg-white text-sm">
                                    <i  class="fa-solid fa-pencil fa-lg mx-2"></i>
                                </td>
                            </tr>
                            </tbody>

                           ))   }
                         
                    </table>
                </div>
                    
            </div>
        </div>
    
    </div>


</div>
</div>
    </div>
  )
}

export default ListarColor

// angular/src/app/components/admin/colores/listar-color/listar-color.component.ts
import { Component, OnInit } from '@angular/core';
import { color } from 'src/app/models/color';
import { CrudServiceService } from 'src/app/services/crud-service.service';

@Component({
  selector: 'app-listar-color',
  templateUrl: './listar-color.component.html',
  styleUrls: ['./listar-color.component.css']
})
export class ListarColorComponent {
  listColores:color[]= [];
  pagActual=1;
  pagNum=5;
  totalPages=0;
  opcion:any="";

  constructor(private _service: CrudServiceService){}

  ngOnInit():void{
    this.obtenerColores();
  }

  obtenerColores(){
    this._service.obtenerTodos(`colores`).subscribe({
      next:(data)=>{
        this.listColores=data;
      },
      error:()=>{

      },
      complete:()=>{
        console.log(this.listColores)
      }
    })
  }


  actualizarEstado(estadoValor:boolean,colorId:any){
    const valor= {estado:estadoValor}
    this._service.actualizar(valor,"colores",colorId).subscribe({
      complete:()=>{
        this.obtenerColores();
      }
    });

  }



}

<div class="flex">
    <app-navbar-lateral></app-navbar-lateral>
    <div class="flex-grow">
        <app-navbar-superior></app-navbar-superior>
        <div class="px-4 py-6 h-20 text-center lg:mt-8">
        <h1 class="text-4xl font-bold text-gray-900">Colores</h1>
    </div>

    <!-- inicio de la tabla -->

    <div class="overflow-hidden mx-auto  w-3/4 px-4 sm:px-8">
        <div class="py-1">
            <div class="my-2 flex flex-row justify-between flex-wrap">
                <a routerLink="/admin/crear-color" class="my-1 text-black bg-yellow-100 hover:bg-yellow-200 w-24 text-sm h-10 rounded-lg font-medium py-2.5 text-center">Crear Color</a>
            </div>
            </div>
            <div class="-mx-4 flex justify-center sm:-mx-8 px-4 sm:px-8 py-4 ">
                <div class="w-full  h-112 shadow rounded-lg ">
                    <div class="h-80 bg-white overflow-auto">
                    <table class="text-center w-full ">
                        <thead>
                            <tr >
                                <th class=" py-3 border-b-2 border-gray-200 bg-gray-100 text-xs font-semibold text-gray-600 uppercase tracking-wider"></th>
                                <th class=" py-3 border-b-2 border-gray-200 bg-gray-100 text-xs font-semibold text-gray-600 uppercase tracking-wider">Nombre</th>
                                <th class=" py-3 border-b-2 border-gray-200 bg-gray-100 text-xs font-semibold text-gray-600 uppercase tracking-wider">Codigo</th>
                                <th class=" py-3 border-b-2 border-gray-200 bg-gray-100 text-xs font-semibold text-gray-600 uppercase tracking-wider">Muestra</th>
                                <th class=" py-3 border-b-2 border-gray-200 bg-gray-100 text-xs font-semibold text-gray-600 uppercase tracking-wider">Estado</th>
                                <th class=" py-3 border-b-2 border-gray-200 bg-gray-100 text-xs font-semibold text-gray-600 uppercase tracking-wider">Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr class="h-14" *ngFor="let color of listColores">
                                <td class="px-5 border-b border-gray-200 bg-white text-sm">
                                    <input #checkEstado type="checkbox" name="" id="" (change)="actualizarEstado(checkEstado.checked,color._id)" [checked]="color.estado===true">
                                </td>
                                <td class="px-5 border-b border-gray-200 bg-white text-sm">
                                    <p class="text-gray-900 whitespace-nowrap">{{color.nombre}}</p>
                                </td>
                                <td class="px-5 border-b border-gray-200 bg-white text-sm">
                                    <p class="text-gray-900 whitespace-nowrap">{{color.codigo}}</p>
                                </td>
    
                                <td class="px-5 border-b border-gray-200 bg-white text-sm">
                                    <p class="text-gray-900 whitespace-nowrap"><i [style.color]="color.codigo" class="fa-solid fa-circle fa-xl"></i></p>
                                </td>
                                <td class="px-5 border-b border-gray-200 bg-white text-sm">
                                    <p class="text-gray-900 whitespace-nowrap" *ngIf="color.estado">Activo</p>
                                    <p class="text-gray-900 whitespace-nowrap" *ngIf="!color.estado">Inactivo</p>
    
                                </td>
                                <td class="px-5 border-b border-gray-200 bg-white text-sm">
                                    <i [routerLink]="['/dashboard/editar-color',color._id]" class="fa-solid fa-pencil fa-lg mx-2"></i>
                                </td>
                            </tr>
                         
                        </tbody>
                    </table>
                </div>
                    
            </div>
        </div>
    
    </div>

  <!-- fin de la tabla -->

</div>
</div>
